// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (factory(global.Arrow = global.Arrow || {}));
}(this, (function (exports) {var n,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function u(){u=function(){};q.Symbol||(q.Symbol=ba)}var ba=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function v(){u();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(this)}});v=function(){}}function ca(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function da(a){v();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}
var ea={NONE:0,0:"NONE",va:1,1:"Null",sa:2,2:"Int",ra:3,3:"FloatingPoint",ma:4,4:"Binary",Aa:5,5:"Utf8",na:6,6:"Bool",oa:7,7:"Decimal",Date:8,8:"Date",xa:9,9:"Time",ya:10,10:"Timestamp",ta:11,11:"Interval",ua:12,12:"List",wa:13,13:"Struct_",za:14,14:"Union",pa:15,15:"FixedSizeBinary",qa:16,16:"FixedSizeList",Map:17,17:"Map"};function fa(){this.a=null;this.b=0}fa.prototype.f=function(a,b){this.b=a;this.a=b;return this};function w(){this.a=null;this.b=0}
w.prototype.f=function(a,b){this.b=a;this.a=b;return this};w.prototype.w=function(){var a=x(this.a,this.b,4);return a?y(this.a,this.b+a):0};w.prototype.O=function(){var a=x(this.a,this.b,6);return a?!!(this.a.g[this.b+a]<<24>>24):!1};function ia(){this.a=null;this.b=0}ia.prototype.f=function(a,b){this.b=a;this.a=b;return this};ia.prototype.precision=function(){var a=x(this.a,this.b,4);return a?A(this.a,this.b+a):0};function B(){this.a=null;this.b=0}B.prototype.f=function(a,b){this.b=a;this.a=b;return this};
function ja(a){return(new B).f(y(a,a.position())+a.position(),a)}B.prototype.w=function(){var a=x(this.a,this.b,4);return a?A(this.a,this.b+a):0};B.prototype.type=function(){var a=x(this.a,this.b,6);return a?A(this.a,this.b+a):0};function ka(){this.a=null;this.b=0}ka.prototype.f=function(a,b){this.b=a;this.a=b;return this};ka.prototype.key=function(a){var b=x(this.a,this.b,4);return b?la(this.a,this.b+b,a):null};
ka.prototype.value=function(a){var b=x(this.a,this.b,6);return b?la(this.a,this.b+b,a):null};function ma(){this.a=null;this.b=0}ma.prototype.f=function(a,b){this.b=a;this.a=b;return this};ma.prototype.id=function(){var a=x(this.a,this.b,4);return a?G(this.a,this.b+a):this.a.A(0,0)};function na(a){var b=x(a.a,a.b,6);return b?(new w).f(I(a.a,a.b+b),a.a):null}function oa(){this.a=null;this.b=0}n=oa.prototype;n.f=function(a,b){this.b=a;this.a=b;return this};
n.name=function(a){var b=x(this.a,this.b,4);return b?la(this.a,this.b+b,a):null};function pa(a){var b=x(a.a,a.b,6);return b?!!(a.a.g[a.b+b]<<24>>24):!1}function qa(a){var b=x(a.a,a.b,8);return b?a.a.g[a.b+b]:0}n.type=function(a){var b=x(this.a,this.b,10);return b?ra(this.a,a,this.b+b):null};function sa(a){var b=x(a.a,a.b,12);return b?(new ma).f(I(a.a,a.b+b),a.a):null}n.children=function(a,b){var c=x(this.a,this.b,14);return c?(b||new oa).f(I(this.a,K(this.a,this.b+c)+4*a),this.a):null};
function ta(a){var b=x(a.a,a.b,14);return b?M(a.a,a.b+b):0}n.ca=function(a,b){var c=x(this.a,this.b,16);return c?(b||new B).f(I(this.a,K(this.a,this.b+c)+4*a),this.a):null};n.da=function(){var a=x(this.a,this.b,16);return a?M(this.a,this.b+a):0};n.W=function(a,b){var c=x(this.a,this.b,18);return c?(b||new ka).f(I(this.a,K(this.a,this.b+c)+4*a),this.a):null};n.X=function(){var a=x(this.a,this.b,18);return a?M(this.a,this.b+a):0};function ua(){this.a=null;this.b=0}
ua.prototype.f=function(a,b){this.b=a;this.a=b;return this};ua.prototype.page=function(){return y(this.a,this.b)};ua.prototype.offset=function(){return G(this.a,this.b+8)};ua.prototype.length=function(){return G(this.a,this.b+16)};function wa(){this.a=null;this.b=0}wa.prototype.f=function(a,b){this.b=a;this.a=b;return this};function xa(a,b){var c=x(a.a,a.b,6);return c?(new oa).f(I(a.a,K(a.a,a.b+c)+4*b),a.a):null}
wa.prototype.W=function(a,b){var c=x(this.a,this.b,8);return c?(b||new ka).f(I(this.a,K(this.a,this.b+c)+4*a),this.a):null};wa.prototype.X=function(){var a=x(this.a,this.b,8);return a?M(this.a,this.b+a):0};function ya(){this.a=null;this.b=0}ya.prototype.f=function(a,b){this.b=a;this.a=b;return this};ya.prototype.version=function(){var a=x(this.a,this.b,4);return a?A(this.a,this.b+a):0};ya.prototype.B=function(a){var b=x(this.a,this.b,6);return b?(a||new wa).f(I(this.a,this.b+b),this.a):null};function za(){this.a=null;this.b=0}za.prototype.f=function(a,b){this.b=a;this.a=b;return this};za.prototype.offset=function(){return G(this.a,this.b)};za.prototype.V=function(){return G(this.a,this.b+16)};var Aa=new Int32Array(2);new Float32Array(Aa.buffer);new Float64Array(Aa.buffer);new Uint16Array((new Uint8Array([1,0])).buffer);function N(a,b){this.low=a|0;this.high=b|0}function Ba(a){return(a.low>>>0)+4294967296*a.high}var Ca=new N(0,0);function Da(a){a=a?a:1024;this.a=new Ea(new Uint8Array(a));this.j=a;this.H=1;this.u=null;this.R=0;this.G=!1;this.ea=0;this.K=[];this.ka=!1}
function Fa(a,b,c){b>a.H&&(a.H=b);for(var e=~(a.a.g.length-a.j+c)+1&b-1;a.j<e+b+c;){var d=a.a.g.length,g=a,h=a.a,f=h.g.length;if(f&3221225472)throw Error("FlatBuffers: cannot grow buffer beyond 2 gigabytes.");var k=f<<1,l=new Ea(new Uint8Array(k));l.setPosition(k-f);l.m().set(h.m(),k-f);g.a=l;a.j+=a.a.g.length-d}for(b=0;b<e;b++)a.a.L(--a.j,0)}n=Da.prototype;n.L=function(a){this.a.L(--this.j,a)};n.S=function(a){this.a.S(this.j-=2,a)};n.v=function(a){this.a.v(this.j-=4,a)};
function Ga(a,b){Fa(a,2,0);a.S(b)}function Ha(a,b,c){if(a.ka||0!=c)Ga(a,c),a.u[b]=a.offset()}n.offset=function(){return this.a.g.length-this.j};function Ia(a){if(a.G)throw Error("FlatBuffers: object serialization must not be nested.");null==a.u&&(a.u=[]);a.R=2;for(var b=0;2>b;b++)a.u[b]=0;a.G=!0;a.ea=a.offset()}
function Ja(a){if(null==a.u||!a.G)throw Error("FlatBuffers: endObject called without startObject");Fa(a,4,0);a.v(0);for(var b=a.offset(),c=a.R-1;0<=c;c--)Ga(a,0!=a.u[c]?b-a.u[c]:0);Ga(a,b-a.ea);Ga(a,2*(a.R+2));var e=0;c=0;a:for(;c<a.K.length;c++){var d=a.a.g.length-a.K[c],g=a.j,h=A(a.a,d);if(h==A(a.a,g)){for(var f=2;f<h;f+=2)if(A(a.a,d+f)!=A(a.a,g+f))continue a;e=a.K[c];break}}e?(a.j=a.a.g.length-b,a.a.v(a.j,e-b)):(a.K.push(a.offset()),a.a.v(a.a.g.length-b,a.offset()-b));a.G=!1;return b}
n.finish=function(a,b){if(b){Fa(this,this.H,8);if(4!=b.length)throw Error("FlatBuffers: file identifier must be length 4");for(var c=3;0<=c;c--)this.L(b.charCodeAt(c))}Fa(this,this.H,4);Fa(this,4,0);this.v(this.offset()-a+4);this.a.setPosition(this.j)};n.A=function(a,b){return 0==a&&0==b?Ca:new N(a,b)};function Ea(a){this.g=a;this.fa=0}n=Ea.prototype;n.m=function(){return this.g};n.position=function(){return this.fa};n.setPosition=function(a){this.fa=a};function Ka(a,b){return a.g[b]}
function A(a,b){return(a.g[b]|a.g[b+1]<<8)<<16>>16}function y(a,b){return a.g[b]|a.g[b+1]<<8|a.g[b+2]<<16|a.g[b+3]<<24}function G(a,b){return new N(y(a,b),y(a,b+4))}n.L=function(a,b){this.g[a]=b};n.S=function(a,b){this.g[a]=b;this.g[a+1]=b>>8};n.v=function(a,b){this.g[a]=b;this.g[a+1]=b>>8;this.g[a+2]=b>>16;this.g[a+3]=b>>24};function x(a,b,c){b-=y(a,b);return c<A(a,b)?A(a,b+c):0}function ra(a,b,c){b.b=c+y(a,c);b.a=a;return b}
function la(a,b,c){b+=y(a,b);var e=y(a,b),d="",g=0;b+=4;if(1===c)return a.g.subarray(b,b+e);for(;g<e;){c=Ka(a,b+g++);if(!(192>c)){var h=Ka(a,b+g++);if(224>c)c=(c&31)<<6|h&63;else{var f=Ka(a,b+g++);if(240>c)c=(c&15)<<12|(h&63)<<6|f&63;else{var k=Ka(a,b+g++);c=(c&7)<<18|(h&63)<<12|(f&63)<<6|k&63}}}65536>c?d+=String.fromCharCode(c):(c-=65536,d+=String.fromCharCode((c>>10)+55296,(c&1023)+56320))}return d}function I(a,b){return b+y(a,b)}function K(a,b){return b+y(a,b)+4}
function M(a,b){return y(a,b+y(a,b))}n.A=function(a,b){return 0==a&&0==b?Ca:new N(a,b)};function La(){this.a=null;this.b=0}La.prototype.f=function(a,b){this.b=a;this.a=b;return this};La.prototype.length=function(){return G(this.a,this.b)};function Oa(){this.a=null;this.b=0}Oa.prototype.f=function(a,b){this.b=a;this.a=b;return this};Oa.prototype.length=function(){var a=x(this.a,this.b,4);return a?G(this.a,this.b+a):this.a.A(0,0)};function Pa(){this.a=null;this.b=0}Pa.prototype.f=function(a,b){this.b=a;this.a=b;return this};
Pa.prototype.id=function(){var a=x(this.a,this.b,4);return a?G(this.a,this.b+a):this.a.A(0,0)};Pa.prototype.data=function(a){var b=x(this.a,this.b,6);return b?(a||new Oa).f(I(this.a,this.b+b),this.a):null};function Qa(){this.a=null;this.b=0}Qa.prototype.f=function(a,b){this.b=a;this.a=b;return this};Qa.prototype.version=function(){var a=x(this.a,this.b,4);return a?A(this.a,this.b+a):0};function Ra(a){var b=x(a.a,a.b,6);return b?a.a.g[a.b+b]:0}
function Sa(a,b){var c=x(a.a,a.b,8);return c?ra(a.a,b,a.b+c):null}Qa.prototype.V=function(){var a=x(this.a,this.b,10);return a?G(this.a,this.b+a):this.a.A(0,0)};function Ta(a){if(void 0===a)return{};if(a===Object(a))return a;throw TypeError("Could not convert argument to dictionary");}function Ua(a){this.s=[].slice.call(a)}Ua.prototype={endOfStream:function(){return!this.s.length},read:function(){return this.s.length?this.s.shift():-1},push:function(a){if(Array.isArray(a))for(;a.length;)this.s.push(a.shift());else this.s.push(a)}};function Va(a){if(a)throw TypeError("Decoder error");return 65533}
function Wa(a,b){if(!(this instanceof Wa))return new Wa(a,b);a=void 0!==a?String(a).toLowerCase():"utf-8";if("utf-8"!==a)throw Error("Encoding not supported. Only utf-8 is supported");b=Ta(b);this.C=this.M=!1;this.D=null;this.T=!!b.fatal;this.U=!!b.ignoreBOM;Object.defineProperty(this,"encoding",{value:"utf-8"});Object.defineProperty(this,"fatal",{value:this.T});Object.defineProperty(this,"ignoreBOM",{value:this.U})}
Wa.prototype={decode:function(a,b){a="object"===typeof a&&a instanceof ArrayBuffer?new Uint8Array(a):"object"===typeof a&&"buffer"in a&&a.buffer instanceof ArrayBuffer?new Uint8Array(a.buffer,a.byteOffset,a.byteLength):new Uint8Array(0);b=Ta(b);this.M||(this.D=new Xa({fatal:this.T}),this.C=!1);this.M=!!b.stream;a=new Ua(a);b=[];for(var c;!a.endOfStream();){c=this.D.ba(a,a.read());if(-1===c)break;null!==c&&(Array.isArray(c)?b.push.apply(b,c):b.push(c))}if(!this.M){do{c=this.D.ba(a,a.read());if(-1===
c)break;null!==c&&(Array.isArray(c)?b.push.apply(b,c):b.push(c))}while(!a.endOfStream());this.D=null}!b.length||-1===["utf-8"].indexOf(this.encoding)||this.U||this.C||(65279===b[0]?(this.C=!0,b.shift()):this.C=!0);a="";for(c=0;c<b.length;++c){var e=b[c];65535>=e?a+=String.fromCharCode(e):(e-=65536,a+=String.fromCharCode((e>>10)+55296,(e&1023)+56320))}return a}};
function Xa(a){var b=a.fatal,c=0,e=0,d=0,g=128,h=191;this.ba=function(a,k){if(-1===k&&0!==d)return d=0,Va(b);if(-1===k)return-1;if(0===d){if(0<=k&&127>=k)return k;if(194<=k&&223>=k)d=1,c=k-192;else if(224<=k&&239>=k)224===k&&(g=160),237===k&&(h=159),d=2,c=k-224;else if(240<=k&&244>=k)240===k&&(g=144),244===k&&(h=143),d=3,c=k-240;else return Va(b);c<<=6*d;return null}if(!(g<=k&&k<=h)){c=d=e=0;g=128;h=191;if(Array.isArray(k))for(;k.length;)a.s.unshift(k.pop());else a.s.unshift(k);return Va(b)}g=128;
h=191;e+=1;c+=k-128<<6*(d-e);if(e!==d)return null;a=c;c=d=e=0;return a}};var Ya=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};function O(a,b){function c(){this.constructor=a}Ya(a,b);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}
function P(a,b){function c(a){return function(b){return e([a,b])}}function e(c){if(g)throw new TypeError("Generator is already executing.");for(;d;)try{if(g=1,h&&(f=h[c[0]&2?"return":c[0]?"throw":"next"])&&!(f=f.call(h,c[1])).done)return f;if(h=0,f)c=[0,f.value];switch(c[0]){case 0:case 1:f=c;break;case 4:return d.label++,{value:c[1],done:!1};case 5:d.label++;h=c[1];c=[0];continue;case 7:c=d.P.pop();d.h.pop();continue;default:if(!(f=d.h,f=0<f.length&&f[f.length-1])&&(6===c[0]||2===c[0])){d=0;continue}if(3===
c[0]&&(!f||c[1]>f[0]&&c[1]<f[3]))d.label=c[1];else if(6===c[0]&&d.label<f[1])d.label=f[1],f=c;else if(f&&d.label<f[2])d.label=f[2],d.P.push(c);else{f[2]&&d.P.pop();d.h.pop();continue}}c=b.call(a,d)}catch(m){c=[6,m],h=0}finally{g=f=0}if(c[0]&5)throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}var d={label:0,c:function(){if(f[0]&1)throw f[1];return f[1]},h:[],P:[]},g,h,f,k;return k={next:c(0),"throw":c(1),"return":c(2)},"function"===typeof Symbol&&(k[Symbol.iterator]=function(){return this}),k}
function Q(a){var b="function"===typeof Symbol&&a[Symbol.iterator],c=0;return b?b.call(a):{next:function(){a&&c>=a.length&&(a=void 0);return{value:a&&a[c++],done:!a}}}}function Za(a,b){var c="function"===typeof Symbol&&a[Symbol.iterator];if(!c)return a;a=c.call(a);var e,d=[];try{for(;(void 0===b||0<b--)&&!(e=a.next()).done;)d.push(e.value)}catch(h){var g={error:h}}finally{try{e&&!e.done&&(c=a["return"])&&c.call(a)}finally{if(g)throw g.error;}}return d}
function R(){for(var a=[],b=0;b<arguments.length;b++)a=a.concat(Za(arguments[b]));return a};function $a(a){var b,c;return P(this,function(e){switch(e.label){case 0:if(!(a.position()<a.g.length&&0<(c=y(a,a.position()))))return[3,2];a.setPosition(a.position()+4);b=(new Qa).f(y(a,a.position())+a.position(),a);a.setPosition(a.position()+c);return[4,b];case 1:return e.c(),[3,0];case 2:return[2]}})}
function ab(a){var b,c,e,d,g,h,f,k,l,m,r;return P(this,function(t){switch(t.label){case 0:b=a.m(),t.label=1;case 1:t.h.push([1,6,7,8]),c=Q($a(a)),e=c.next(),t.label=2;case 2:if(e.done)return[3,5];d=e.value;g=Ra(d);f=h=void 0;if(3===g)f=Sa(d,new Oa);else if(2===g)k=Sa(d,new Pa),h=Ba(k.id()).toString(),f=k.data();else return[3,4];return[4,{id:h,data:f,m:b,offset:b.byteOffset+a.position()}];case 3:t.c(),a.setPosition(a.position()+d.V().low),t.label=4;case 4:return e=c.next(),[3,2];case 5:return[3,8];
case 6:return l=t.c(),m={error:l},[3,8];case 7:try{e&&!e.done&&(r=c.return)&&r.call(c)}finally{if(m)throw m.error;}return[7];case 8:return[2]}})};for(var bb=new Uint8Array(6),cb=0;6>cb;cb+=1)bb[cb]="ARROW1".charCodeAt(cb);function db(a,b){void 0===b&&(b=0);for(var c=-1,e=bb.length;++c<e;)if(bb[c]!==a[b+c])return!1;return!0}var eb=bb.length,fb=eb+4,gb=2*eb+4;
function hb(){var a=[];for(b=0;b<arguments.length;b++)a[b]=arguments[b];var b,c,e,d,g,h,f,k,l,m,r,t,z,p,C,H,E,F,D,L,U,ha,Ma,va,Na,rb;return P(this,function(b){switch(b.label){case 0:b.h.push([0,23,24,25]),c=Q(a),e=c.next(),b.label=1;case 1:if(e.done)return[3,22];d=e.value;g=d.g.length;f=h=void 0;if(g<gb||!db(d.m(),0)||!db(d.m(),g-eb)||1>(h=y(d,f=g-fb))&&h+gb>g)throw Error("Invalid file");d.setPosition(f-h);var J=d;k=(new ya).f(y(J,J.position())+J.position(),J);l=k.B();m=-1;r=(J=x(k.a,k.b,8))?M(k.a,
k.b+J):0;b.label=2;case 2:if(!(++m<r))return[3,11];t=(J=x(k.a,k.b,8))?(new za).f(K(k.a,k.b+J)+24*m,k.a):null;d.setPosition(t.offset().low);b.label=3;case 3:b.h.push([3,8,9,10]),z=Q(ab(d)),p=z.next(),b.label=4;case 4:if(p.done)return[3,7];C=p.value;return[4,{B:l,N:C}];case 5:return b.c(),[3,7];case 6:return p=z.next(),[3,4];case 7:return[3,10];case 8:return H=b.c(),Ma={error:H},[3,10];case 9:try{p&&!p.done&&(va=z.return)&&va.call(z)}finally{if(Ma)throw Ma.error;}return[7];case 10:return[3,2];case 11:m=
-1,r=(J=x(k.a,k.b,10))?M(k.a,k.b+J):0,b.label=12;case 12:if(!(++m<r))return[3,21];t=(J=x(k.a,k.b,10))?(new za).f(K(k.a,k.b+J)+24*m,k.a):null;d.setPosition(t.offset().low);b.label=13;case 13:b.h.push([13,18,19,20]),E=Q(ab(d)),F=E.next(),b.label=14;case 14:if(F.done)return[3,17];C=F.value;return[4,{B:l,N:C}];case 15:return b.c(),[3,17];case 16:return F=E.next(),[3,14];case 17:return[3,20];case 18:return D=b.c(),Na={error:D},[3,20];case 19:try{F&&!F.done&&(rb=E.return)&&rb.call(E)}finally{if(Na)throw Na.error;
}return[7];case 20:return[3,12];case 21:return e=c.next(),[3,1];case 22:return[3,25];case 23:return L=b.c(),U={error:L},[3,25];case 24:try{e&&!e.done&&(ha=c.return)&&ha.call(c)}finally{if(U)throw U.error;}return[7];case 25:return[2]}})};function ib(){var a=[];for(b=0;b<arguments.length;b++)a[b]=arguments[b];var b,c,e,d,g,h,f,k,l,m,r,t,z,p,C,H,E,F,D,L;return P(this,function(b){switch(b.label){case 0:if(!a.length||db(a[0].m(),0))throw Error("Invalid Arrow Stream");b.label=1;case 1:b.h.push([1,19,20,21]),c=Q($a(a[0])),e=c.next(),b.label=2;case 2:if(e.done)return[3,18];d=e.value;if(1!==Ra(d))return[3,17];g=Sa(d,new wa);b.label=3;case 3:b.h.push([3,14,15,16]),h=Q(a),f=h.next(),b.label=4;case 4:if(f.done)return[3,13];k=f.value;b.label=
5;case 5:b.h.push([5,10,11,12]),l=Q(ab(k)),m=l.next(),b.label=6;case 6:if(m.done)return[3,9];r=m.value;return[4,{B:g,N:r}];case 7:b.c(),b.label=8;case 8:return m=l.next(),[3,6];case 9:return[3,12];case 10:return t=b.c(),D={error:t},[3,12];case 11:try{m&&!m.done&&(L=l.return)&&L.call(l)}finally{if(D)throw D.error;}return[7];case 12:return f=h.next(),[3,4];case 13:return[3,16];case 14:return z=b.c(),E={error:z},[3,16];case 15:try{f&&!f.done&&(F=h.return)&&F.call(h)}finally{if(E)throw E.error;}return[7];
case 16:return[3,18];case 17:return e=c.next(),[3,2];case 18:return[3,21];case 19:return p=b.c(),C={error:p},[3,21];case 20:try{e&&!e.done&&(H=c.return)&&H.call(c)}finally{if(C)throw C.error;}return[7];case 21:return[2]}})};function jb(a,b,c){var e=b||0;c=c===c&&"number"==typeof c?c:a;0>c&&(c=a+c);0>e&&(e=a- -1*e%a);c<e&&(e=c,c=b);a=!isFinite(a=c-e)||0>a?0:a;return[e,a]}
var S=function(){function a(){}a.create=function(a,c){for(var b=[],d=2;d<arguments.length;d++)b[d-2]=arguments[d];b=new (this.bind.apply(this,R([void 0],b)));b.length=c;b.name=a.name();b.type=ea[qa(a)];if(0<(d=a.X())){var g=0,h=b.props=new Map;do{var f=a.W(g);h[f.key()]=f.value()}while(++g<d)}return b};a.from=function(b,c){for(var e=[],d=2;d<arguments.length;d++)e[d-2]=arguments[d];e=new (this.bind.apply(this,R([void 0],e)));e.length=c;b.name!==a.Z&&(e.name=b.name);b.type!==a.aa&&(e.type=b.type);
b.props!==a.$&&(e.props=b.props);return e};a.prototype.get=function(){return null};a.prototype.concat=function(a){return a};a.prototype.slice=function(a,c,e){var b=this.ha;a=Za(jb(b*this.length,b*(a||0),b*c),2);return this.ga(a[0],a[1],e)};a.prototype.ga=function(a,c){for(var b=Array(c),d=-1,g=this.length;++d<c;)b[d]=this.get((d+a)%g);return b};u();v();a.prototype[Symbol.iterator]=function(){var a,c;return P(this,function(b){switch(b.label){case 0:a=-1,c=this.length,b.label=1;case 1:return++a<c?[4,
this.get(a)]:[3,4];case 2:b.c(),b.label=3;case 3:return[3,1];case 4:return[2]}})};a.Z="";a.$=new Map;a.aa=ea[0];return a}();n=S.prototype;n.length=0;n.ha=1;n.name=S.Z;n.type=S.aa;n.props=S.$;var mb=function(a){function b(){for(var b=[],e=0;e<arguments.length;e++)b[e]=arguments[e];e=a.call(this)||this;e.l=b.filter(Boolean);return e}O(b,a);Object.defineProperty(b.prototype,"arrayType",{get:function(){return this.i},enumerable:!0,configurable:!0});b.prototype.get=function(a){for(var b,c,g=this.l,h=-1;(b=g[++h])&&(c=b.length)<=a&&0<=(a-=c););return b&&-1<a?b[a]:null};b.prototype.ga=function(a,b,d){var c,e=a,f;a=this.l;var k=this.i;for(d=(d||0)-1;(c=a[++d])&&(f=c.length)<=e&&0<=(e-=f););if(c&&
-1<e){f=0;var l=a.length,m=Array.isArray(c)?kb:lb,r=k.prototype.subarray||k.prototype.slice;e=c=r.call(c,e,e+b);if(c.length<b)for(e=new k(b);(f=m(c,e,f))<b;)c=a[d=(d+1)%l],c=r.call(c,0,Math.min(c.length,b-f));return e}return new k(0)};u();v();b.prototype[Symbol.iterator]=function(){var a,b,d,g,h,f,k,l,m;return P(this,function(c){switch(c.label){case 0:a=-1,b=this,d=b.l,g=b.length,h=-1,f=d.length,c.label=1;case 1:if(!(++h<f))return[3,6];k=d[h];l=-1;m=k.length;c.label=2;case 2:return++a<g&&++l<m?[4,
k[l]]:[3,5];case 3:c.c(),c.label=4;case 4:return[3,2];case 5:return[3,1];case 6:return[2]}})};return b}(S),T=function(a){function b(){for(var b=[],e=0;e<arguments.length;e++)b[e]=arguments[e];b=a.apply(this,R(b))||this;b.length=b.l.reduce(function(a,b){return a+b.length},0);return b}O(b,a);b.from=function(a){return a instanceof b?a:a===b.F?a:a instanceof Uint8Array?new b(a):a instanceof Array?new b(b.pack(a)):a instanceof S?new b(b.pack(a)):b.F};b.pack=function(a){var b=[],c,g=0,h=0,f=0;try{for(var k=
Q(a),l=k.next();!l.done;l=k.next())l.value&&(f|=1<<h),8===++h&&(b[g++]=f,f=h=0)}catch(t){var m={error:t}}finally{try{l&&!l.done&&(r=k.return)&&r.call(k)}finally{if(m)throw m.error;}}if(0===g||0<h)b[g++]=f;if(g%8&&(c=c=g+8-g%8)){do b[g]=0;while(++g<c)}return new Uint8Array(b);var r};b.prototype.get=function(a){for(var b,c,g=this.l,h=-1;(b=g[++h])&&(c=b.length)<=a&&0<=(a-=c););return!(!b||0>a||0===(b[a>>3|0]&1<<a%8))};b.prototype.set=function(a,b){for(var c,e,h=this.l,f=-1;(c=h[++f])&&(e=c.length)<=
a&&0<=(a-=e););c&&-1<a&&(b?c[a>>3|0]|=1<<a%8:c[a>>3|0]&=~(1<<a%8))};b.prototype.concat=function(a){return new (b.bind.apply(b,R([void 0],this.l,a.l)))};u();v();b.prototype[Symbol.iterator]=function(){var b,e,d,g,h,f,k;return P(this,function(c){switch(c.label){case 0:c.h.push([0,7,8,9]),u(),v(),b=Q(a.prototype[Symbol.iterator].call(this)),e=b.next(),c.label=1;case 1:if(e.done)return[3,6];d=e.value;g=-1;c.label=2;case 2:return 8>++g?[4,0!==(d&1<<g)]:[3,5];case 3:c.c(),c.label=4;case 4:return[3,2];case 5:return e=
b.next(),[3,1];case 6:return[3,9];case 7:return h=c.c(),f={error:h},[3,9];case 8:try{e&&!e.done&&(k=b.return)&&k.call(b)}finally{if(f)throw f.error;}return[7];case 9:return[2]}})};b.F=new (function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);b.prototype.get=function(){return!0};u();v();b.prototype[Symbol.iterator]=function(){return P(this,function(a){switch(a.label){case 0:return[4,!0];case 1:a.c(),a.label=2;case 2:return[3,0];case 3:return[2]}})};return b}(S));return b}(mb),
nb=function(a){function b(b){for(var c=[],d=1;d<arguments.length;d++)c[d-1]=arguments[d];c=a.apply(this,R(c))||this;b&&(c.validity=T.from(b));return c}O(b,a);b.prototype.concat=function(a){return(b=this.constructor).from.apply(b,R([this,this.length+a.length,this.validity.concat(a.validity)],this.l,a.l));var b};return b}(mb),ob=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);b.prototype.get=function(b){return this.validity.get(b)?new Date(Math.pow(2,32)*a.prototype.get.call(this,
2*b+1)+a.prototype.get.call(this,2*b)):null};u();v();b.prototype[Symbol.iterator]=function(){var b,e,d,g,h;return P(this,function(c){switch(c.label){case 0:u(),v(),g=a.prototype[Symbol.iterator].call(this),u(),v(),h=this.validity[Symbol.iterator](),c.label=1;case 1:return(b=h.next()).done||(e=g.next()).done||(d=g.next()).done?[3,3]:[4,b.value?new Date(Math.pow(2,32)*d.value+e.value):null];case 2:return c.c(),[3,1];case 3:return[2]}})};return b}(nb),pb=function(a){function b(){return null!==a&&a.apply(this,
arguments)||this}O(b,a);b.prototype.get=function(a,b){void 0===b&&(b=!1);for(var c,e,h=-1,f=this.l;(c=f[++h])&&(e=c.length)<=a&&0<=(a-=e););return b?c&&-1<a?[c[a+h],h]:[0,-1]:c&&-1<a?c[a+h]:null};u();v();b.prototype[Symbol.iterator]=function(){var a,b,d,g,h,f,k;return P(this,function(c){switch(c.label){case 0:a=new Int32Array(2),b=this.l,d=-1,g=b.length,c.label=1;case 1:if(!(++d<g))return[3,7];h=b[d];f=-1;k=h.length-1;c.label=2;case 2:if(!(++f<k))return[3,6];a[1]=d;a[0]=h[f];return[4,a];case 3:return c.c(),
[4,h[f+1]];case 4:c.c(),c.label=5;case 5:return[3,2];case 6:return[3,1];case 7:return[2]}})};return b}(nb),V=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);b.prototype.get=function(b){return this.validity.get(b)?a.prototype.get.call(this,b):null};u();v();b.prototype[Symbol.iterator]=function(){var b,e,d,g,h;return P(this,function(c){switch(c.label){case 0:return d=this.validity,u(),v(),g=a.prototype[Symbol.iterator].call(this),d!==T.F?[3,2]:[5,Q(g)];case 1:return c.c(),
[3,5];case 2:u(),v(),h=d[Symbol.iterator](),c.label=3;case 3:return(b=h.next()).done||(e=g.next()).done?[3,5]:[4,b.value?e.value:null];case 4:return c.c(),[3,3];case 5:return[2]}})};return b}(nb),qb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);b.prototype.get=function(b){return this.validity.get(b)?new N(a.prototype.get.call(this,2*b),a.prototype.get.call(this,2*b+1)):null};u();v();b.prototype[Symbol.iterator]=function(){var b,e,d,g,h;return P(this,function(c){switch(c.label){case 0:u(),
v(),g=a.prototype[Symbol.iterator].call(this),u(),v(),h=this.validity[Symbol.iterator](),c.label=1;case 1:return(b=h.next()).done||(e=g.next()).done||(d=g.next()).done?[3,3]:[4,b.value?new N(e.value,d.value):null];case 2:return c.c(),[3,1];case 3:return[2]}})};return b}(nb),sb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(V),tb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(V),ub=function(a){function b(){return null!==
a&&a.apply(this,arguments)||this}O(b,a);return b}(V),vb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(qb),wb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(V),xb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(V),yb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(V),zb=function(a){function b(){return null!==a&&a.apply(this,arguments)||
this}O(b,a);return b}(qb),Ab=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(V),Bb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(V);qb.prototype.ha=2;S.prototype.l=[];S.prototype.validity=T.F;mb.prototype.i=Array;T.prototype.i=Uint8Array;sb.prototype.i=Int8Array;tb.prototype.i=Int16Array;ub.prototype.i=Int32Array;vb.prototype.i=Int32Array;wb.prototype.i=Uint8Array;xb.prototype.i=Uint16Array;yb.prototype.i=Uint32Array;
zb.prototype.i=Uint32Array;ob.prototype.i=Uint32Array;pb.prototype.i=Int32Array;Ab.prototype.i=Float32Array;Bb.prototype.i=Float64Array;function kb(a,b,c){for(var e=0,d=a.length;e<d;)b[c++]=a[e++];return c}function lb(a,b,c){return b.set(a,c)||c+a.length};var Cb=function(a){function b(b){for(var c=[],d=1;d<arguments.length;d++)c[d-1]=arguments[d];d=a.call(this)||this;d.J=c;d.length=Math.max.apply(Math,R([0],c.map(function(a){return a.length})));b&&(d.validity=T.from(b));return d}O(b,a);b.prototype.get=function(a){return this.validity.get(a)?this.J.map(function(b){return b.get(a)}):null};b.prototype.concat=function(a){return b.from.apply(b,R([this,this.length+a.length,this.validity.concat(a.validity)],this.J.map(function(b,c){return b.concat(a.J[c])})))};
return b}(S);var Db=function(a){function b(b,e){var c=a.call(this)||this;c.keys=b;c.data=e;c.length=b&&b.length||0;return c}O(b,a);b.prototype.index=function(a){return this.keys.get(a)};b.prototype.value=function(a){return this.data.get(a)};b.prototype.get=function(a){return this.value(this.index(a))};b.prototype.concat=function(a){return b.from(this,this.length+a.length,this.keys.concat(a.keys),this.data)};u();v();b.prototype[Symbol.iterator]=function(){var a,b,d,g,h,f,k;return P(this,function(c){switch(c.label){case 0:a=
this.data,c.label=1;case 1:c.h.push([1,6,7,8]),b=Q(this.keys),d=b.next(),c.label=2;case 2:if(d.done)return[3,5];g=d.value;return[4,a.get(g)];case 3:c.c(),c.label=4;case 4:return d=b.next(),[3,2];case 5:return[3,8];case 6:return h=c.c(),f={error:h},[3,8];case 7:try{d&&!d.done&&(k=b.return)&&k.call(b)}finally{if(f)throw f.error;}return[7];case 8:return[2]}})};return b}(S);var Eb=function(a){function b(b,e,d){var c=a.call(this)||this;c.values=e;c.I=d;b&&(c.validity=T.from(b));return c}O(b,a);b.prototype.get=function(a){var b,c,g,h=this.I;return this.validity.get(a)&&null!==(g=h.get(a+1))&&(f=h.get(a,!0),k=Za(f,2),c=k[0],b=k[1],f)&&-1<b?this.values.slice(c,g,b):null;var f,k};b.prototype.concat=function(a){return this.constructor.from(this,this.length+a.length,this.validity.concat(a.validity),this.values.concat(a.values),this.I.concat(a.I))};u();v();b.prototype[Symbol.iterator]=
function(){var a,b,d,g,h,f;return P(this,function(c){switch(c.label){case 0:g=this.values,u(),v(),h=this.I[Symbol.iterator](),u(),v(),f=this.validity[Symbol.iterator](),c.label=1;case 1:return(a=f.next()).done||(b=h.next()).done||(d=h.next()).done?[3,3]:[4,a.value?g.slice(b.value[0],d.value,b.value[1]):null];case 2:return c.c(),[3,1];case 3:return[2]}})};return b}(S),Fb=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}O(b,a);return b}(Eb),Gb=function(a){function b(){return null!==
a&&a.apply(this,arguments)||this}O(b,a);b.prototype.get=function(c){return(c=a.prototype.get.call(this,c))?b.Y.decode(c):null};u();v();b.prototype[Symbol.iterator]=function(){var c,e,d,g,h,f,k;return P(this,function(l){switch(l.label){case 0:c=b.Y,l.label=1;case 1:l.h.push([1,6,7,8]),u(),v(),e=Q(a.prototype[Symbol.iterator].call(this)),d=e.next(),l.label=2;case 2:if(d.done)return[3,5];g=d.value;return[4,g?c.decode(g):null];case 3:l.c(),l.label=4;case 4:return d=e.next(),[3,2];case 5:return[3,8];case 6:return h=
l.c(),f={error:h},[3,8];case 7:try{d&&!d.done&&(k=e.return)&&k.call(e)}finally{if(f)throw f.error;}return[7];case 8:return[2]}})};b.Y=new Wa("utf-8");return b}(Eb),Hb=function(a){function b(b,e,d){var c=a.call(this)||this;c.values=d;c.size=Math.abs(b|0)||1;e&&(c.validity=T.from(e));return c}O(b,a);b.prototype.get=function(a){return this.validity.get(a)?this.values.slice(this.size*a,this.size*(a+1)):null};b.prototype.concat=function(a){return b.from(this,this.length+a.length,this.size,this.validity.concat(a.validity),
this.values.concat(a.values))};u();v();b.prototype[Symbol.iterator]=function(){var a,b,d,g,h,f,k;return P(this,function(c){switch(c.label){case 0:b=-1,d=this,g=d.size,h=d.length,f=d.values,u(),v(),k=this.validity[Symbol.iterator](),c.label=1;case 1:return!(a=k.next()).done&&++b<h?[4,a.value?f.slice(g*b,g*(b+1)):null]:[3,3];case 2:return c.c(),[3,1];case 3:return[2]}})};return b}(S);function Ib(a,b,c,e){var d;if(!(d=Jb(a,b,c,e))){d=qa(a);var g=Kb[d];if(!g)throw Error('Unrecognized vector name "'+ea[d]+'" type "'+d+'"');d=g(a,b,c,e)}return d}function Jb(a,b,c,e){var d;if(e&&(d=sa(a))){var g=Ba(d.id()).toString();d=na(d)||{w:function(){return 32},O:function(){return!0}};var h=Lb(a,d);b=Mb(h,b,c,null,d);return Db.create(a,b.length,b,e[g])}}
var Nb=[Uint8Array,Uint8Array,Uint8Array,Uint8Array],Ob=[Uint32Array,Uint32Array,Uint32Array,Uint32Array],Pb=W.bind(null,[Int8Array,Int16Array,Int32Array,Int32Array],null),Qb=W.bind(null,[Uint8Array,Uint16Array,Uint32Array,Uint32Array],null),Rb=W.bind(null,Ob,null),Sb=W.bind(null,[Int8Array,Int16Array,Float32Array,Float64Array],null),Tb=W.bind(null,Ob,null),Ub=W.bind(null,Nb,null),Vb=W.bind(null,Nb,[Int32Array,Int32Array,Int32Array,Int32Array]),Xb=(Wb={},Wb[1]=Ab,Wb[2]=Bb,Wb),Yb=[[wb,sb],[xb,tb],
[yb,ub],[zb,vb]];function Mb(a,b,c,e,d){d=d||a.type(new w);return d.O()?Zb(a,b,c,e,d):$b(a,b,c,e,d)}var Zb=X(Pb,ac),$b=X(Qb,ac);function ac(a,b,c,e,d,g){g=g||a.type(new w);return(Yb[g.w()>>4]||Yb[3])[+g.O()].create(a,b,e,c||d)}
var bc=X(Sb,function(a,b,c,e){var d=a.type(new ia);return Xb[d.precision()].create(a,b,e,c)}),cc=X(Rb,function(a,b,c,e){return ob.create(a,b,e,c)}),dc=X(Vb,function(a,b,c,e,d){d=new Int32Array(d.buffer,d.byteOffset,b+1);return Gb.create(a,b,e,wb.create(a,c.length,null,c),pb.create(a,b+1,null,d))}),ec=X(Tb,function(a,b,c,e,d,g,h,f,k){c=new Int32Array(d.buffer,d.byteOffset,b+1);return Fb.create(a,b,e,Ib(a.children(0),h,f,k),pb.create(a,b+1,null,c))}),fc=X(Tb,function(a,b,c,e,d,g,h,f,k){c=a.type(new fa);
d=x(c.a,c.b,4);return Hb.create(a,b,d?y(c.a,c.b+d):0,e,Ib(a.children(0),h,f,k))}),gc=X(Tb,function(a,b,c,e,d,g,h,f,k){c=[];d=-1;for(g=ta(a);++d<g;)c[d]=Ib(a.children(d),h,f,k);return Cb.create.apply(Cb,R([a,b,e],c))}),Kb=(Y={},Y[2]=Mb,Y[8]=cc,Y[12]=ec,Y[5]=dc,Y[13]=gc,Y[3]=bc,Y[16]=fc,Y);
function X(a,b){return function(c,e,d,g,h){var f=e.data,k=c.da();var l=d.la++;var m=x(f.a,f.b,6);l=m?(new La).f(K(f.a,f.b+m)+16*l,f.a):null;var r,t,z,p,C,H;m=l.length().low;for(var E=-1;++E<k;){var F=c.ca(E);var D=d.ja++;var L=x(f.a,f.b,8);D=L?(new ua).f(K(f.a,f.b+L)+24*D,f.a):null;3===(p=F.type())||0>=(H=D.length().low)||0>=(C=F.w())||(1===p?r=a(e,p,C,D.offset().low,H):0===p?t=a(e,p,C,D.offset().low,H):0<G(l.a,l.b+8).low&&(z=Ub(e,p,C,D.offset().low,m)))}return b(c,m,r,z,t,h,e,d,g)}}
function W(a,b,c,e,d,g,h){var f=c.m.buffer,k=f.byteLength;c=c.offset+g;a=0===e&&b||a;d=a[d>>4]||a[3];return new d(f,c,(c+h<=k?h:k-c)/d.BYTES_PER_ELEMENT)}function Lb(a,b){var c=[],e=new Da;pa(a)&&(Ia(e),Ha(e,0,8),Ha(e,1,2),e.finish(Ja(e)),c.push(ja(e.a)),e=new Da);Ia(e);Ha(e,0,b.w());Ha(e,1,1);e.finish(Ja(e));c.push(ja(e.a));return Object.create(a,{ca:{value:function(a){return c[a]}},da:{value:function(){return c.length}}})}var Wb,Y;function hc(a,b,c,e){var d,g,h,f,k,l,m,r,t,z;return P(this,function(p){switch(p.label){case 0:return(g=a&&sa(a))&&b.id===(d=Ba(g.id()).toString())?[4,[d,Ib(a,b,c,null)]]:[3,2];case 1:return p.c(),[2];case 2:h=-1,f=a&&ta(a)||0,p.label=3;case 3:if(!(++h<f))return[3,12];p.label=4;case 4:p.h.push([4,9,10,11]),k=Q(hc(a.children(h),b,c,e)),l=k.next(),p.label=5;case 5:if(l.done)return[3,8];m=l.value;return[4,m];case 6:return p.c(),[2];case 7:return l=k.next(),[3,5];case 8:return[3,11];case 9:return r=p.c(),
t={error:r},[3,11];case 10:try{l&&!l.done&&(z=k.return)&&z.call(k)}finally{if(t)throw t.error;}return[7];case 11:return[3,3];case 12:return[2]}})};function ic(){var a=[];for(b=0;b<arguments.length;b++)a[b]=arguments[b];var b;return P(this,function(b){switch(b.label){case 0:return b.h.push([0,2,,7]),[5,Q(hb.apply(void 0,R(a)))];case 1:return b.c(),[3,7];case 2:b.c(),b.label=3;case 3:return b.h.push([3,5,,6]),[5,Q(ib.apply(void 0,R(a)))];case 4:return b.c(),[3,6];case 5:throw b.c(),Error("Invalid Arrow buffer");case 6:return[3,7];case 7:return[2]}})}
function jc(){var a=[];for(b=0;b<arguments.length;b++)a[b]=arguments[b];var b,c,e,d,g,h,f,k,l,m,r,t,z,p,C,H,E,F,D,L,U,ha;return P(this,function(b){switch(b.label){case 0:c={},e=a.map(kc),b.label=1;case 1:b.h.push([1,7,8,9]),d=Q(ic.apply(void 0,R(e))),g=d.next(),b.label=2;case 2:if(g.done)return[3,6];h=g.value;f=h.B;k=h.N;l=[];m={la:0,ja:0};r=-1;t=(b=x(f.a,f.b,6))?M(f.a,f.b+b):0;if(!k.id)return[3,3];for(;++r<t;)try{for(z=Q(hc(xa(f,r),k,m,c)),p=z.next();!p.done;p=z.next())C=Za(p.value,2),H=C[0],E=C[1],
c[H]=c[H]&&c[H].concat(E)||E}catch(va){U={error:va}}finally{try{p&&!p.done&&(ha=z.return)&&ha.call(z)}finally{if(U)throw U.error;}}return[3,5];case 3:for(;++r<t;)l[r]=Ib(xa(f,r),k,m,c);return[4,l];case 4:b.c(),b.label=5;case 5:return g=d.next(),[3,2];case 6:return[3,9];case 7:return F=b.c(),D={error:F},[3,9];case 8:try{g&&!g.done&&(L=d.return)&&L.call(d)}finally{if(D)throw D.error;}return[7];case 9:return[2]}})}
function kc(a){var b=a||new Uint8Array(0);if("string"===typeof a){b=new Uint8Array(a.length);for(var c=-1,e=a.length;++c<e;)b[c]=a.charCodeAt(c)}return new Ea(b)};var pc=function(){function a(a){this.o=a||[];this.length=Math.max.apply(Math,R(this.o.map(function(a){return a.length})));this.ia=this.o.reduce(function(a,b){return(a[b.name]=b)&&a||a},{})}a.from=function(){function b(a){d=d?d.map(function(b,c){return b.concat(a[c])}):a}for(var c=[],e=0;e<arguments.length;e++)c[e]=arguments[e];var d;try{for(var g=Q(jc.apply(void 0,R(c))),h=g.next();!h.done;h=g.next())b(h.value)}catch(l){var f={error:l}}finally{try{h&&!h.done&&(k=g.return)&&k.call(g)}finally{if(f)throw f.error;
}}return new a(d);var k};a.Ba=function(b){return new a(b.J)};u();v();a.prototype[Symbol.iterator]=function(){var a,c,e;return P(this,function(b){switch(b.label){case 0:a=this.o,c=-1,e=this.length,b.label=1;case 1:return++c<e?[4,lc(c,a)]:[3,4];case 2:b.c(),b.label=3;case 3:return[3,1];case 4:return[2]}})};a.prototype.rows=function(a,c,e){var b,g,h,f,k,l,m;return P(this,function(d){switch(d.label){case 0:b=a,g=c,"boolean"===typeof a?(e=a,b=g,g=void 0):"boolean"===typeof c&&(e=c,g=void 0),h=-1,f=this.length,
k=Za(jb(f,b,g),2),l=k[0],m=k[1],d.label=1;case 1:return++h<m?[4,this.getRow((h+l)%f,e)]:[3,3];case 2:return d.c(),[3,1];case 3:return[2]}})};a.prototype.cols=function(a,c){var b,d,g,h,f,k;return P(this,function(e){switch(e.label){case 0:e.h.push([0,5,6,7]),b=Q(this.o.slice(a,c)),d=b.next(),e.label=1;case 1:if(d.done)return[3,4];g=d.value;return[4,g];case 2:e.c(),e.label=3;case 3:return d=b.next(),[3,1];case 4:return[3,7];case 5:return h=e.c(),f={error:h},[3,7];case 6:try{d&&!d.done&&(k=b.return)&&
k.call(b)}finally{if(f)throw f.error;}return[7];case 7:return[2]}})};a.prototype.getRow=function(a,c){return(c&&mc||nc)(a,this.o)};a.prototype.getCell=function(a,c){return this.getColumn(a).get(c)};a.prototype.getCellAt=function(a,c){return this.getColumnAt(a).get(c)};a.prototype.getColumn=function(a){return this.ia[a]};a.prototype.getColumnAt=function(a){return this.o[a]};a.prototype.toString=function(a){var b="object"===typeof a?a&&!!a.index:"boolean"===typeof a?!!a:!1,e=this.length;if(0>=e)return"";
a=[];e=Array(e+1);e[0]=this.o.map(function(a){return a.name});b&&e[0].unshift("Index");for(var d=-1,g=e.length-1;++d<g;)e[d+1]=this.getRow(d,!0),b&&e[d+1].unshift(d);d=-1;for(g=e.length;++d<g;){b=e[d];for(var h=-1,f=b.length;++h<f;){var k=b[h]=""+b[h];a[h]=a[h]?Math.max(a[h],k.length):k.length}}d=-1;for(g=e.length;++d<g;){b=e[d];h=-1;for(f=b.length;++h<f;)b[h]=oc(b[h],a[h]);e[d]=b.join(", ")}return e.join("\n")};return a}();pc.prototype.length=0;
function oc(a,b){return(Array(b+1).join(" ")+a).slice(-1*b)}function lc(a,b){return b.reduce(function(b,e){return b.set(e.name,e.get(a))},new Map)}function nc(a,b){return b.reduce(function(b,e){return(b[e.name]=e.get(a))&&b||b},Object.create(null))}function mc(a,b){return b.reduce(function(b,e,d){return(b[d]=e.get(a))&&b||b},Array(b.length))};try{var Z=eval("exports");"object"===typeof Z&&(Z.Table=pc,Z.readBuffers=jc,Z.Vector=S,Z.BitVector=T,Z.ListVector=Fb,Z.Utf8Vector=Gb,Z.DateVector=ob,Z.IndexVector=pb,Z.TypedVector=nb,Z.Int8Vector=sb,Z.Int16Vector=tb,Z.Int32Vector=ub,Z.Int64Vector=vb,Z.Uint8Vector=wb,Z.Uint16Vector=xb,Z.Uint32Vector=yb,Z.Uint64Vector=zb,Z.Float32Vector=Ab,Z.Float64Vector=Bb,Z.StructVector=Cb,Z.DictionaryVector=Db,Z.FixedSizeListVector=Hb)}catch(a){};}.bind(this))));

//# sourceMappingURL=Arrow.js.map
